<?php

namespace AppBundle\Repository;

/**
 * AssignmentEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentEventRepository extends \Doctrine\ORM\EntityRepository
{
}
