<?php

namespace AppBundle\Repository;

/**
 * AssignmentEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAssignmentEventsForStudent($id)
    {
        return $this->_em->createQuery("SELECT ae
            FROM AppBundle\Entity\AssignmentEvent ae
            JOIN ae.assignment a
            JOIN a.subject su
            JOIN su.lectures l
            JOIN l.group g
            JOIN g.students st
            JOIN st.user u
            where u.id = :id
            ")->setParameter('id', $id)->getResult();
    }
}
