<?php

namespace AppBundle\Repository;

/**
 * StudentAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStudentGrades($id)
    {
        return $this->_em->createQuery("SELECT g, a, su
            FROM AppBundle\Entity\Grade g
            JOIN g.student st
            JOIN g.assignment a
            JOIN a.subject su
            JOIN st.user u
            WHERE u.id = :id
            ")->setParameter('id', $id)->getResult();
    }

    public function getStudentsGradesByLecture($lectureId)
    {
        return $this->_em->createQuery("SELECT g, st, a, gr, l, lt, ltl
            FROM AppBundle\Entity\Grade g
            JOIN g.student st
            JOIN g.assignment a
            JOIN st.groups gr
            JOIN gr.lectures l
            JOIN l.subject sl
            JOIN a.subject sa
            JOIN a.lectureType lt
            JOIN l.lectureType ltl
            WHERE l.id = :lectureId AND lt.id = ltl.id AND sl.id = sa.id
            ")->setParameter('lectureId', $lectureId)->getResult();
    }
}
