<?php

namespace AppBundle\Repository;

/**
 * Group_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group_Repository extends \Doctrine\ORM\EntityRepository
{
}
