<?php

namespace AppBundle\Repository;

/**
 * LectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLecturesForLecturer($id)
    {
        return $this->_em->createQuery("SELECT l
            FROM AppBundle\Entity\Lecture l
            JOIN l.lecturer lr
            JOIN lr.user u
            where u.id = :id
            ")->setParameter('id', $id)->getResult();
    }
}
