<?php

namespace AppBundle\Repository;

/**
 * LectureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
