<?php

namespace AppBundle\Repository;

/**
 * LectureDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureDateRepository extends \Doctrine\ORM\EntityRepository
{
}
