<?php

namespace AppBundle\Repository;

/**
 * LecturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturerRepository extends \Doctrine\ORM\EntityRepository
{
}
