<?php

namespace AppBundle\Repository;

/**
 * LectureDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureDateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLectureDatesByUser($id)
    {
        return $this->_em->createQuery("SELECT ld
            FROM AppBundle\Entity\LectureDate ld
            JOIN ld.lecture l
            JOIN l.group g
            JOIN g.students s
            where s.id = :id
            ")->setParameter('id', $id)->getResult();
    }
}
