<?php

namespace AppBundle\Repository;

/**
 * StudentAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
